sudo: false
language: python
python:
- '2.7'
- '3.4'
before_install:
- if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh
  -O miniconda.sh; else wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
addons:
  apt:
    packages:
    - pandoc
install:
- conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION numpy scipy nose
  pandas matplotlib
- source activate test-environment
- pip install pypandoc
- pip install -r requirements.txt
- pip install .
- pip install coveralls
script:
- nosetests test --with-coverage --cover-package=stancache && ./lint.sh
after_success: coveralls
deploy:
  provider: pypi
  user: jackinovik
  password:
    secure: ACFt7zARWoiF+a7ov7LVAmm6Ow3NeOt54rCJhWm0l81dQb+21t+wSPjL2q640V+GFEVQ6arbq2R5aWzZhVGpuslLTxIo2b73Tb7cKs9/Uy2nFH4fVtSsagvDoVJyqCL6I7uW8RRPGTaMZzRf7RUKnf2GTx7Bro9l2MmMmDAfm2PYzfIh2u8CNMfZMHQsb/dK9cJijzXz6+Y7X3A2X6puzr770PjTcYlNz7dxHBfSW/2nyEueSSmUTLx7Jmok0gTMkEqJniYfqUKz0jvVCiJxLUtC2zXAxrJaXvMRtr15vjQR6nYJZwaQgxKn3RmVDEYlu2GLKrt/+oZByvnQ960vHQf22TRKIYK+HZ86DhTr43U+OwSSZlM+MWInjFAK8ehdyP4m4fG6r0upnyaVnKfIaCaLVHqfG3yXew3JnTlPdsPzl06qC4GXndMGplLUXcMXdoTT+AQCsr/JHKg5JhnYFnZERodGfxW7tDPriGfC/pekKJV1Am6ETcC01SKbK5/+FMXMo1w3FT+Pf6buUB0pSysuRdPG4KE0gu82+FIrV4cJ5qm001lXQkWGE7SVa/UU63B1B4FnT5Ht38M4PdlRtMTPfV+i1Y47Z5WL+ETMNPZ+OAlvOAYCMKxmaP1Dg1B0xcx+kzcvVIv6eHYXS2P7fwtG2J/IsN7xzNBn/cG0KWQ=
  on:
    branch: master
    tags: true
  skip_existing: true
